# Generated by Django 6.0.3 on 2026-05-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailmessage_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='emails/'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.tag'),
        ),
    ]
